# Voidbound Nova idle policy
#
# 5 min  -> dim display
# 10 min -> lock session
# NEVER  -> DPMS off
# NEVER  -> automatic suspend

$LOCK_CMD = hyde-shell lockscreen.sh

general {
    lock_cmd = $LOCK_CMD
    ignore_dbus_inhibit = false
}

# Dim after 5 minutes
listener {
    timeout = 300
    on-timeout = brightnessctl -s && brightnessctl s 20%
    on-resume = brightnessctl -r
}

# Lock after 10 minutes
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}
